"""
Unit tests for Woolworths NZ API module (woolworths_api.py).

These tests are fully offline:
    - Nearby stores are loaded from fixture/stores_fixture.csv
      (a real slice of the CDX site-location API, captured by
      fixture/generate_fixtures.py).
    - Product responses are loaded from fixture/response_example1.json
      (a real product search response from the live Woolworths API).
    - The non-food filtering test uses a hand-crafted product dict
      that is loaded from fixture/nonfood_product_example.json,
      which is also generated from the same live response structure.

All assertions reference fixture data directly so that test outcomes are
deterministic and traceable to the actual API responses captured.
"""

import json
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

FIXTURE_DIR = Path(__file__).resolve().parent / "fixture"

from NZMealOptimiser.pricing.woolworths_api import (
    is_food_department,
    get_nearby_stores,
    set_store_context,
    search_products,
    create_session,
)


def _load_json(filename):
    """Load a JSON fixture file from the fixture directory."""
    with open(FIXTURE_DIR / filename, "r", encoding="utf-8") as f:
        return json.load(f)


class TestIsFoodDepartment:
    """Tests for is_food_department()."""

    @staticmethod
    def _make_product(dept_ids):
        """Create a minimal product dict with the given department ids."""
        return {"departments": [{"id": d} for d in dept_ids]}

    def test_food_department_included(self):
        """A product in a food department (id=4 Fridge & Deli) should be included.

        Department 4 is used in the real fixture (response_example1.json)
        for milk products.
        """
        product = self._make_product([4])  # Fridge & Deli
        assert is_food_department(product) is True

    def test_non_food_department_excluded(self):
        """A product in a non-food department (id=11 Household) must be excluded."""
        product = self._make_product([11])
        assert is_food_department(product) is False

    def test_pet_department_excluded(self):
        """A product in the Pet department (id=13) must be excluded."""
        product = self._make_product([13])
        assert is_food_department(product) is False

    def test_empty_departments_included(self):
        """Products with no department info are assumed food (included).

        This matches the real ad/promo item (index 4 in the fixture)
        which has no departments and should be treated as non-food
        only if it has a SKU — actually is_food_department returns True
        for empty departments, so it would be included unless filtered
        elsewhere (search_products checks SKU).
        """
        product = {"departments": []}
        assert is_food_department(product) is True

    def test_mixed_food_and_non_food_excluded(self):
        """If ANY department is non-food, the product is excluded."""
        product = self._make_product([4, 11])  # Food + Household
        assert is_food_department(product) is False


class TestGetNearbyStores:
    """Tests for get_nearby_stores() using real fixture coordinates.

    Sources stores directly from data/woolworths_stores.csv (generated by
    fetch_store_data(), keyed on extra1). The tests patch
    woolworths_api.STORE_CSV with the offline fixture stores_fixture.csv
    (5 Nelson stores, id=extra1).

    Reference point: Nelson Junction Woolworths (-41.2977069, 173.241518)
    """

    @patch("NZMealOptimiser.pricing.woolworths_api.STORE_CSV", FIXTURE_DIR / "stores_fixture.csv")
    def test_nearby_stores_from_reference_point(self):
        """4 fixture stores are within 5 km of Nelson Junction. The result
        must be sorted by distance ascending; Nelson Junction itself is
        the closest (~0 km) and is keyed by its fulfilmentStoreId (extra1).
        """
        ref = _load_json("nearby_stores_example.json")
        user_lat = ref["reference_point"]["lat"]
        user_lon = ref["reference_point"]["lon"]

        nearby = get_nearby_stores(user_lat, user_lon, max_dist_km=5)
        assert len(nearby) == 4

        # Results must be sorted by distance ascending
        distances = [s["distance_km"] for s in nearby]
        assert distances == sorted(distances)

        # The closest store should be Nelson Junction itself (distance ~0)
        assert abs(nearby[0]["distance_km"] - 0.0) < 0.1
        assert nearby[0]["name"] == "Nelson Junction Woolworths"

    @patch("NZMealOptimiser.pricing.woolworths_api.STORE_CSV", FIXTURE_DIR / "stores_fixture.csv")
    def test_no_nearby_stores_far_point(self):
        """A query point in Auckland (>500km away) must return no stores.

        The fixture stores are in Nelson (lat ~-41.3). Querying from
        Auckland (lat ~-36.8) is ~500 km away.
        """
        user_lat, user_lon = -36.8485, 174.7635  # Auckland CBD
        nearby = get_nearby_stores(user_lat, user_lon, max_dist_km=5)
        assert len(nearby) == 0

    @patch("NZMealOptimiser.pricing.woolworths_api.STORE_CSV", FIXTURE_DIR / "stores_fixture.csv")
    def test_nearby_stores_all_within_radius(self):
        """Every returned store must be within the specified radius."""
        ref = _load_json("nearby_stores_example.json")
        user_lat = ref["reference_point"]["lat"]
        user_lon = ref["reference_point"]["lon"]

        nearby = get_nearby_stores(user_lat, user_lon, max_dist_km=5)
        for store in nearby:
            assert store["distance_km"] <= 5.0

    @patch("NZMealOptimiser.pricing.woolworths_api.STORE_CSV", FIXTURE_DIR / "stores_fixture.csv")
    def test_nearby_stores_keyed_on_extra1(self):
        """Each nearby store's 'store_id' must be extra1 (fulfilmentStoreId).

        After the pickupAddressId retirement, store_id == fulfilmentStoreId
        for every store returned by get_nearby_stores().
        """
        ref = _load_json("nearby_stores_example.json")
        user_lat = ref["reference_point"]["lat"]
        user_lon = ref["reference_point"]["lon"]

        nearby = get_nearby_stores(user_lat, user_lon, max_dist_km=5)
        for store in nearby:
            assert "store_id" in store
            assert store["store_id"] == str(store["fulfilmentStoreId"])

    @patch("NZMealOptimiser.pricing.woolworths_api.STORE_CSV", FIXTURE_DIR / "stores_fixture.csv")
    def test_nearby_stores_no_pickup_address_id_field(self):
        """get_nearby_stores() no longer returns a pickupAddressId field.

        The extra2->extra1 indirection is retired; store identity is extra1.
        """
        ref = _load_json("nearby_stores_example.json")
        user_lat = ref["reference_point"]["lat"]
        user_lon = ref["reference_point"]["lon"]

        nearby = get_nearby_stores(user_lat, user_lon, max_dist_km=5)
        for store in nearby:
            assert "pickupAddressId" not in store


class TestSearchProductsFiltering:
    """Tests for search_products() filtering logic using a mocked session.

    The mocked session.get returns the real captured response from
    fixture/response_example1.json (a milk search at Nelson Junction store).
    The fixture contains 15 items: 14 food products across departments 4
    (Fridge & Deli) and 7 (Pantry), plus 1 ad/promo item with empty SKU
    and empty departments.
    """

    def _mock_session(self):
        """Build a MagicMock session whose .get returns the captured
        response_example1.json fixture."""
        fixture = _load_json("response_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = fixture
        session = MagicMock()
        session.get.return_value = mock_resp
        return session

    def test_search_products_includes_food(self):
        """search_products with food_only=True must include milk products.

        The captured response contains food items (department 4, Fridge & Deli
        and department 7, Pantry) plus 1 ad/promo item with no SKU and no
        departments. Since is_food_department returns True for empty
        departments (items with no dept are assumed food), the ad item is
        also included.
        """
        session = self._mock_session()
        products = search_products(session, "milk", food_only=True)
        names = [p["name"] for p in products]
        # All products should be milk-related
        assert any("milk" in n.lower() for n in names)
        # food_only=True excludes items with non-food departments (Household, Pet, etc.)
        # but does NOT exclude items with empty SKU or empty departments (those are treated as food)
        # The ad item (index 4, sku="", departments=[]) is included because is_food_department([]) returns True
        for p in products:
            if p["department"]:
                assert p["department"] in ("Fridge & Deli", "Pantry")  # Food depts in fixture

    def test_search_products_empty_sku_included_with_food_filter(self):
        """With food_only=True, items with empty SKU are still included.

        search_products only filters by department, not SKU. The ad item
        (index 4) has empty SKU and empty departments, which is treated
        as food (is_food_department returns True for empty departments).
        So empty SKU items ARE included when food_only=True.
        """
        session = self._mock_session()
        products = search_products(session, "milk", food_only=True)
        skus = [p["sku"] for p in products]
        # The ad item has empty SKU — it IS included because food_only
        # only filters by department, and empty departments pass the food check
        empty_sku_count = sum(1 for s in skus if not s)
        assert empty_sku_count >= 1

    def test_search_products_no_food_filter_returns_all_with_sku(self):
        """Without food_only, all items with valid SKUs are returned."""
        session = self._mock_session()
        products = search_products(session, "milk", food_only=False)
        # 15 items total, 1 has empty SKU (ad item)
        # search_products with food_only=False returns all items
        assert len(products) == 15

    def test_search_products_normalizes_fields(self):
        """search_products must flatten the raw API response into the
        normalized dict structure expected by build_woolworths_row().

        Specifically: salePrice, volumeSize, cupMeasure, cupListPrice,
        isSpecial, and department (string name).
        """
        session = self._mock_session()
        products = search_products(session, "milk", food_only=False)
        first = products[0]

        # Verify all normalized keys are present
        expected_keys = {"sku", "name", "salePrice", "originalPrice",
                         "isSpecial", "unitPrice", "volumeSize",
                         "cupMeasure", "cupListPrice", "url",
                         "imageUrl", "department"}
        assert expected_keys.issubset(set(first.keys()))

        # Verify specific values from the first item (anchor milk standard blue, 3L)
        assert first["sku"] == "705692"
        assert first["salePrice"] == 9.07
        assert first["volumeSize"] == "3L"
        assert first["cupMeasure"] == "1L"
        assert first["cupListPrice"] == 3.02
        assert first["department"] == "Fridge & Deli"

    def test_search_products_preserves_all_products(self):
        """search_products with food_only=False must return all 15 items
        from the captured response (no filtering)."""
        session = self._mock_session()
        products = search_products(session, "milk", food_only=False)
        assert len(products) == 15


class TestSetStoreContext:
    """Tests for set_store_context() — the per-store cookie injection mechanism.

    set_store_context() does two things:
    1. Constructs the cw-lrkswrdjp cookie from the store's fulfilmentStoreId
       (extra1 — supplied directly by the caller; no mapping lookup).
    2. GETs /api/v1/shell to VERIFY the cookie took effect — it checks that
       the shell's fulfilment.fulfilmentStoreId matches the injected value.
       If the shell still shows the default store (9171), it raises RuntimeError.

    After the pickupAddressId retirement, set_store_context takes extra1
    (fulfilmentStoreId) directly and does NOT read STORE_JSON. These tests
    use the REAL captured shell response from fixture/shell_example1.json
    (Nelson Junction Woolworths, fsId=9290) and mock the session.get() call
    that hits /api/v1/shell.
    """

    def test_cookie_value_constructed_correctly(self):
        """The cw-lrkswrdjp cookie must be 'dm-Pickup,f-{fsid},s-38'.

        For Nelson Junction Woolworths (extra1=9290):
            cookie = "dm-Pickup,f-9290,s-38"
        """
        session = MagicMock()
        shell_fixture = _load_json("shell_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = shell_fixture
        session.get.return_value = mock_resp

        result = set_store_context(session, "9290")
        assert result["fulfilmentStoreId"] == 9290
        assert result["method"] == "Pickup"

        # Verify the cookie was set with the correct value
        session.cookies.set.assert_called_once()
        call_args = session.cookies.set.call_args
        # cookies.set is called as set("cw-lrkswrdjp", "dm-Pickup,f-9290,s-38", domain=..., path=...)
        assert call_args.args[0] == "cw-lrkswrdjp"
        assert call_args.args[1] == "dm-Pickup,f-9290,s-38"
        assert call_args.kwargs.get("domain") == "www.woolworths.co.nz"
        assert call_args.kwargs.get("path") == "/"

    def test_shell_validation_passes(self):
        """When the shell returns the expected fulfilmentStoreId, no error is raised.

        Uses the captured shell fixture where the injected store (9290) Nelson
        Junction Woolworths correctly appears as the active store context.
        """
        session = MagicMock()
        shell_fixture = _load_json("shell_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = shell_fixture
        session.get.return_value = mock_resp

        # This should NOT raise RuntimeError
        result = set_store_context(session, "9290")
        assert result["fulfilmentStoreId"] == 9290

    def test_default_store_shell_raises_runtime_error(self):
        """When the shell still shows the default store (9171), RuntimeError is raised.

        This simulates the case where the cookie injection fails. We mock
        the shell response to show fulfilmentStoreId=9171 (the default).
        """
        session = MagicMock()
        # Mock a shell response that shows the DEFAULT store (9171)
        fake_shell = {
            "context": {
                "fulfilment": {
                    "fulfilmentStoreId": 9171,  # default store — proves cookie didn't work
                    "method": "Courier",
                }
            }
        }
        mock_resp = MagicMock()
        mock_resp.json.return_value = fake_shell
        session.get.return_value = mock_resp

        with pytest.raises(RuntimeError, match="Cookie not accepted"):
            set_store_context(session, "9290")

    def test_cookie_injected_before_shell_validation(self):
        """The cookie must be set BEFORE the shell validation call.

        set_store_context() first sets the cookie, then calls shell to verify.
        We verify by checking the call order on the session mock.
        """
        session = MagicMock()
        shell_fixture = _load_json("shell_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = shell_fixture
        session.get.return_value = mock_resp

        set_store_context(session, "9290")

        # Verify call order: cookies.set called before session.get(shell URL)
        # Use mock_calls to find each call's position in the recorded sequence.
        mock_calls = [repr(c) for c in session.mock_calls]
        cookie_set_idx = next(
            (i for i, c in enumerate(mock_calls) if "cookies.set" in c), None,
        )
        shell_get_idx = next(
            (i for i, c in enumerate(mock_calls)
             if ".get(" in c and "/shell" in c and i > (cookie_set_idx or 0)), None,
        )

        assert cookie_set_idx is not None, "cookies.set was not called"
        assert shell_get_idx is not None, "session.get(shell) was not called"
        assert cookie_set_idx < shell_get_idx, "Cookie must be set before shell validation GET"

    def test_shell_is_called_with_correct_url(self):
        """The shell validation GET must be called against /api/v1/shell."""
        session = MagicMock()
        shell_fixture = _load_json("shell_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = shell_fixture
        session.get.return_value = mock_resp

        result = set_store_context(session, "9290")

        # Verify the shell endpoint was called with the exact /api/v1/shell URL.
        session.get.assert_called_once()
        called_url = session.get.call_args[0][0]
        assert called_url == "https://www.woolworths.co.nz/api/v1/shell"

    def test_cookie_takes_int_fulfilment_store_id(self):
        """set_store_context accepts fulfilmentStoreId as an int (extra1)."""
        session = MagicMock()
        shell_fixture = _load_json("shell_example1.json")
        mock_resp = MagicMock()
        mock_resp.json.return_value = shell_fixture
        session.get.return_value = mock_resp

        result = set_store_context(session, 9290)  # int, not str
        assert result["fulfilmentStoreId"] == 9290
        call_args = session.cookies.set.call_args
        assert call_args.args[1] == "dm-Pickup,f-9290,s-38"