"""
Pak'nSave Test Fixture Generator (Live API Capture)
Last run: 10/08/2026 (fixtures are regenerated by running this script live)
===================================================
Generates traceable test data files by making REAL HTTP requests to the
live Pak'nSave Edge and Mobile APIs and the public website store-finder.

Every fixture file produced here is captured from a live API response —
there is no synthetic or hand-written data. This guarantees that the
tests in scripts/paknsave/tests/ exercise the parsers, filters, and
mergers against data that matches real production response shapes.

Fixtures produced:
    fixture/
    ├── edge_store_list_example.json     Edge API store list
    │                                     (GET {EDGE_BASE}/store)
    ├── edge_store_list_example_meta.json Metadata tracing endpoint/store count
    ├── edge_search_pass1_example.json   Edge Pass 1 relevance search ("milk")
    │                                     (POST {EDGE_BASE}/search/products/query/index/products-index)
    ├── edge_search_pass1_meta.json      Metadata tracing Pass 1 capture (endpoint, store)
    ├── edge_search_pass2_example.json   Edge Pass 2 per-store pricing ("milk")
    │                                     (POST {EDGE_BASE}/search/paginated/products)
    ├── edge_search_pass2_meta.json      Metadata tracing Pass 2 capture (endpoint, filters)
    ├── mobile_login_example.json        Mobile guest login response
    │                                     (POST {MOBILE_BASE}/mobile/user/login/guest)
    ├── mobile_login_meta.json           Metadata tracing mobile auth endpoint
    ├── mobile_stores_example.json       Mobile physical store list
    │                                     (GET {MOBILE_BASE}/mobile/store/physical)
    ├── mobile_stores_meta.json          Metadata tracing mobile store endpoint/store count
    ├── mobile_search_example.json       Mobile product search ("milk")
    │                                     (POST {MOBILE_BASE}/mobile/ecomm-products/PNS/{store_id}/search)
    ├── mobile_search_meta.json          Metadata tracing mobile search endpoint (store, query)
    ├── store_finder_page_example.json   Website store-finder HTML containing __NEXT_DATA__
    │                                     (GET {WEB_BASE}/store-finder)
    └── store_finder_meta.json           Metadata tracing store-finder capture

Usage (requires internet access to Pak'nSave APIs):
    python scripts/paknsave/fixture/generate_fixtures.py

The script is idempotent: re-running it overwrites all fixture files.
"""

import json
import re
import requests
import cloudscraper
from pathlib import Path

# Fixture directory lives alongside this script
FIXTURE_DIR = Path(__file__).resolve().parent
WEB_BASE = "https://www.paknsave.co.nz"
EDGE_BASE = "https://api-prod.paknsave.co.nz/v1/edge"
MOBILE_BASE = "https://api-prod.prod.fsniwaikato.kiwi/prod"


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------
def _get_website_jwt():
    """Get website JWT (fs-user-token) via public website flow.

    Mirrors the authentication used by PaknSaveEdgeAPI.authenticate():
    a POST to /api/user/get-current-user with an established session
    returns a cookie containing the JWT bearer token for Edge API calls.

    Returns:
        session: an authenticated requests.Session
        token: the fs-user-token JWT string
    """
    print("  [Auth] Getting website JWT...")
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Origin": WEB_BASE,
        "Referer": WEB_BASE + "/",
    })
    session.get(WEB_BASE, timeout=30)
    r = session.post(f"{WEB_BASE}/api/user/get-current-user", json={}, timeout=30)
    r.raise_for_status()
    token = session.cookies.get("fs-user-token")
    if not token:
        raise RuntimeError("Failed to get fs-user-token cookie")
    return session, token


# ---------------------------------------------------------------------------
# Fixture 1: edge_store_list_example.json
# ---------------------------------------------------------------------------
# Captures the real Edge API store list and the first stores returned.
# Tests load_stores(), find_nearby_stores(), and store schema handling.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Fixture 2: edge_search_pass1_example.json
# ---------------------------------------------------------------------------
# Captures the real Edge Pass 1 relevance search response ("milk").
#
# Source: real Pak'nSave Edge API, searching for "milk".
# Endpoint: POST {EDGE_BASE}/search/products/query/index/products-index
#
# The response includes hits sorted by relevance, each with productID,
# name, price, and categoryTrees. Tests verify:
#   - pass1_relevance_search_hits() correctly parses the hits list.
#   - The relevance-sorted hits contain expected milk-like products.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Fixture 3: edge_search_pass2_example.json
# ---------------------------------------------------------------------------
# Captures the real Edge Pass 2 per-store pricing response ("milk").
#
# Source: same store as Pass 1, with Algolia filters on productIDs.
# Endpoint: POST {EDGE_BASE}/search/paginated/products
# Sort: PRICE_ASC
#
# The response includes products sorted by unit price ascending, each with
# singlePrice (in cents) and comparativePrice (per-unit details). Tests verify:
#   - pass2_per_store_pricing() correctly parses the products list.
#   - extract_price() handles price conversion (cents -> dollars).
# ---------------------------------------------------------------------------

def capture_edge_fixtures():
    """Capture Edge API store list, Pass 1 relevance search, and Pass 2 pricing.

    Uses a real website JWT for Edge API authentication. Searches for "milk"
    to produce fixtures exercising the two-pass search pipeline.

    Returns:
        store_id: the ID of the first store retrieved (used by mobile fixtures).
    """
    print("\n--- Capturing Edge API Fixtures ---")
    session, token = _get_website_jwt()
    headers = {
        "Authorization": f"Bearer {token}",
        "access_token": token,
        "Content-Type": "application/json",
        "Origin": WEB_BASE,
        "Referer": f"{WEB_BASE}/",
        "User-Agent": "Mozilla/5.0",
    }

    # --- Edge Store List ---
    print("  Fetching Edge store list...")
    r = requests.get(f"{EDGE_BASE}/store", headers=headers, timeout=30)
    r.raise_for_status()
    stores_data = r.json()

    # Validate that the API returned stores. The first store will be used
    # as the context for the subsequent search requests.
    stores = stores_data.get("stores", [])
    if not stores:
        raise RuntimeError("No stores returned from Edge API")
    test_store = stores[0]
    store_id = test_store["id"]
    store_name = test_store["name"]
    region = test_store.get("region", "NI")

    # Save the full store list payload to disk for load_stores tests.
    path = FIXTURE_DIR / "edge_store_list_example.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(stores_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path}")

    # Trace metadata so tests can identify which endpoint/store produced this.
    meta_path = FIXTURE_DIR / "edge_store_list_example_meta.json"
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{EDGE_BASE}/store",
            "store_count": len(stores),
            "first_store_id": store_id,
            "first_store_name": store_name,
            "notes": "Edge API store list captured from live Pak'nSave API."
        }, f, indent=2)
    print(f"    Wrote {meta_path}")

    # Cookies required for Edge search requests (per-store context)
    store_cookies = {
        "eCom_STORE_ID": store_id,
        "STORE_ID_V2": f"{store_id}|False",
        "Region": region,
    }
    search_headers = {
        "Authorization": f"Bearer {token}",
        "access_token": token,
        "Content-Type": "application/json",
        "Origin": WEB_BASE,
        "Referer": f"{WEB_BASE}/shop",
        "User-Agent": "Mozilla/5.0",
    }

    # --- Edge Pass 1: Relevance Search ("milk") ---
    # Passes a query to the Algolia-backed products-index, returning relevance-sorted hits.
    print(f"  Fetching Edge Pass 1 search ('milk') for store {store_name} ({store_id})...")
    p1_payload = {
        "algoliaQuery": {"query": "milk"},
        "page": 0,
        "hitsPerPage": 20,
        "storeId": store_id,
    }
    r1 = requests.post(
        f"{EDGE_BASE}/search/products/query/index/products-index",
        headers=search_headers,
        json=p1_payload,
        cookies=store_cookies,
        timeout=30,
    )
    r1.raise_for_status()
    p1_data = r1.json()

    # Save the Pass 1 response (hits with productID, name, price, categoryTrees).
    path1 = FIXTURE_DIR / "edge_search_pass1_example.json"
    with open(path1, "w", encoding="utf-8") as f:
        json.dump(p1_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path1}")

    with open(FIXTURE_DIR / "edge_search_pass1_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{EDGE_BASE}/search/products/query/index/products-index",
            "store_id": store_id,
            "store_name": store_name,
            "query": "milk",
            "hits_count": len(p1_data.get("hits", [])),
            "notes": "Edge Pass 1 relevance search captured from live API."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'edge_search_pass1_meta.json'}")

    # Extract productIDs for the Pass 2 filter query
    hits = p1_data.get("hits", [])
    product_ids = [h["productID"] for h in hits[:10]]

    # --- Edge Pass 2: Per-Store Pricing ---
    # Re-queries with Algolia filters on the productIDs and sorts by PRICE_ASC.
    print(f"  Fetching Edge Pass 2 pricing for {len(product_ids)} products...")
    filter_str = " OR ".join(f"productID:{pid}" for pid in product_ids) if product_ids else "productID:none"
    p2_payload = {
        "algoliaQuery": {"query": "milk", "filters": filter_str},
        "page": 0,
        "hitsPerPage": 50,
        "storeId": store_id,
        "sortOrder": "PRICE_ASC",
    }
    r2 = requests.post(
        f"{EDGE_BASE}/search/paginated/products",
        headers=search_headers,
        json=p2_payload,
        cookies=store_cookies,
        timeout=30,
    )
    r2.raise_for_status()
    p2_data = r2.json()

    # Save the Pass 2 response (products with singlePrice/comparativePrice in cents).
    path2 = FIXTURE_DIR / "edge_search_pass2_example.json"
    with open(path2, "w", encoding="utf-8") as f:
        json.dump(p2_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path2}")

    with open(FIXTURE_DIR / "edge_search_pass2_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{EDGE_BASE}/search/paginated/products",
            "store_id": store_id,
            "store_name": store_name,
            "filters": filter_str,
            "products_count": len(p2_data.get("products", [])),
            "notes": "Edge Pass 2 per-store pricing captured from live API."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'edge_search_pass2_meta.json'}")

    return store_id


# ---------------------------------------------------------------------------
# Fixture 4: mobile_login_example.json
# ---------------------------------------------------------------------------
# Captures the Mobile API guest login token response.
# Tests ensure_token() and the bearer-token authentication flow.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Fixture 5: mobile_stores_example.json
# ---------------------------------------------------------------------------
# Captures the full Mobile API physical store list.
# Tests get_stores() and load_stores() integration.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Fixture 6: mobile_search_example.json
# ---------------------------------------------------------------------------
# Captures the Mobile API product search response ("milk").
# Tests search_products() normalisation and is_food_product() filtering.
# ---------------------------------------------------------------------------

def capture_mobile_fixtures(store_id):
    """Capture Mobile API login, physical stores, and product search responses.

    Uses cloudscraper to bypass anti-bot protection. Searches for "milk"
    to produce a fixture exercising the single-pass Mobile search flow.

    Args:
        store_id: the Edge store ID used for the Mobile search context.
    """
    print("\n--- Capturing Mobile API Fixtures ---")
    scraper = cloudscraper.create_scraper()

    # --- Mobile Guest Login ---
    # A guest POST returns an access_token used for subsequent authenticated requests.
    print("  Fetching Mobile guest login token...")
    r = scraper.post(
        f"{MOBILE_BASE}/mobile/user/login/guest",
        json={"banner": "PNS"},
        headers={"User-Agent": "PAKnSAVEApp/4.32.0", "Content-Type": "application/json"},
    )
    r.raise_for_status()
    login_data = r.json()
    token = login_data["access_token"]

    # Save the login token response (access_token expires after 30 minutes).
    path = FIXTURE_DIR / "mobile_login_example.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(login_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path}")

    with open(FIXTURE_DIR / "mobile_login_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{MOBILE_BASE}/mobile/user/login/guest",
            "notes": "Mobile guest token authentication captured from live API."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'mobile_login_meta.json'}")

    # Auth headers for subsequent Mobile requests
    auth_headers = {
        "Authorization": f"Bearer {token}",
        "access_token": token,
        "User-Agent": "PAKnSAVEApp/4.32.0",
        "Content-Type": "application/json",
    }

    # --- Mobile Physical Stores ---
    print("  Fetching Mobile physical store list...")
    r2 = scraper.get(f"{MOBILE_BASE}/mobile/store/physical", headers=auth_headers, timeout=30)
    r2.raise_for_status()
    stores_data = r2.json()

    path2 = FIXTURE_DIR / "mobile_stores_example.json"
    with open(path2, "w", encoding="utf-8") as f:
        json.dump(stores_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path2}")

    with open(FIXTURE_DIR / "mobile_stores_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{MOBILE_BASE}/mobile/store/physical",
            "store_count": len(stores_data.get("stores", [])),
            "notes": "Mobile store list captured from live API."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'mobile_stores_meta.json'}")

    # --- Mobile Product Search ("milk") ---
    # Searches for "milk" under the PNS banner for the specified store.
    print(f"  Fetching Mobile product search ('milk') for store {store_id}...")
    r3 = scraper.post(
        f"{MOBILE_BASE}/mobile/ecomm-products/PNS/{store_id}/search?q=milk&hitsPerPage=20",
        headers=auth_headers,
        json=[],
    )
    r3.raise_for_status()
    search_data = r3.json()

    path3 = FIXTURE_DIR / "mobile_search_example.json"
    with open(path3, "w", encoding="utf-8") as f:
        json.dump(search_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path3}")

    with open(FIXTURE_DIR / "mobile_search_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{MOBILE_BASE}/mobile/ecomm-products/PNS/{store_id}/search",
            "store_id": store_id,
            "query": "milk",
            "products_count": len(search_data) if isinstance(search_data, list) else len(search_data.get("products", [])),
            "notes": "Mobile product search response captured from live API."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'mobile_search_meta.json'}")


# ---------------------------------------------------------------------------
# Fixture 7: store_finder_page_example.json
# ---------------------------------------------------------------------------
# Captures the website store-finder page HTML containing __NEXT_DATA__.
# Tests store-finder parsing and coordinate extraction from the Next.js payload.
# ---------------------------------------------------------------------------

def capture_store_finder_fixtures():
    """Capture the store-finder page HTML containing __NEXT_DATA__.

    Extracts the embedded Next.js JSON payload which contains all store
    location data for the website store-finder.
    """
    print("\n--- Capturing Store Finder Fixture ---")
    scraper = cloudscraper.create_scraper()
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0"}

    print("  Fetching store-finder page...")
    r = scraper.get(f"{WEB_BASE}/store-finder", headers=headers)
    r.raise_for_status()

    # The __NEXT_DATA__ script tag contains the full Next.js payload including
    # all store locations — no separate API call is needed.
    match = re.search(
        r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
        r.text,
        re.DOTALL,
    )
    if not match:
        raise RuntimeError("Could not find __NEXT_DATA__ in store-finder page")

    next_data = json.loads(match.group(1))

    path = FIXTURE_DIR / "store_finder_page_example.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(next_data, f, indent=2, ensure_ascii=False)
    print(f"    Wrote {path}")

    with open(FIXTURE_DIR / "store_finder_meta.json", "w", encoding="utf-8") as f:
        json.dump({
            "endpoint": f"{WEB_BASE}/store-finder",
            "notes": "__NEXT_DATA__ extracted from Pak'nSave store-finder page."
        }, f, indent=2)
    print(f"    Wrote {FIXTURE_DIR / 'store_finder_meta.json'}")


def main():
    """Capture all Pak'nSave fixtures in dependency order: Edge → Mobile → Store Finder."""
    print("=" * 60)
    print("Pak'nSave Test Fixture Generator")
    print("Capturing REAL data from live Pak'nSave APIs & website")
    print(f"Target directory: {FIXTURE_DIR}")
    print("=" * 60)

    store_id = capture_edge_fixtures()
    capture_mobile_fixtures(store_id)
    capture_store_finder_fixtures()

    print("\n" + "=" * 60)
    print("[OK] All Pak'nSave fixtures captured successfully.")
    print("=" * 60)


if __name__ == "__main__":
    main()
