"""
Woolworths NZ API Module
========================
Provides functions for interacting with the Woolworths NZ (Countdown) backend API.

Per-store pricing is achieved by injecting a cw-lrkswrdjp cookie constructed from
the store's **fulfilmentStoreId (extra1)** — the canonical store identity keyed
directly in data/woolworths_stores.csv.

Key functions:
    create_session()            - Create a seeded requests.Session with required headers
    set_store_context()         - Inject per-store cookie for pricing (takes fulfilment_store_id)
    search_products()           - Keyword search against the product catalogue
    find_cheapest()             - Search and return the lowest-priced result
    get_nearby_stores()         - Haversine distance filter on store coordinates

Data files:
    data/woolworths_stores.csv  - Canonical store list keyed on extra1 (fulfilmentStoreId)
                                  with lat/lon. Generated by woolworths_setup.fetch_store_data().
                                  Excludes shut-down stores (9285, 9035) and null-extra1 sites.

Reference: Woolworths_API.md (1290+ lines of endpoint documentation)
"""

import csv
import requests

from NZMealOptimiser import DATA_DIR
from .optimiser_utils import haversine

BASE_URL = "https://www.woolworths.co.nz/api/v1"
SITE_URL = "https://www.woolworths.co.nz/"

HEADERS = {
    "x-requested-with": "??",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-NZ,en;q=0.9",
    "Referer": "https://www.woolworths.co.nz/",
}

STORE_CSV = DATA_DIR / "woolworths_stores.csv"

# Department IDs for non-food categories (excluded when food_only=True)
# Source: /api/v1/shell → mainNavs[1] → Browse departments
NON_FOOD_DEPARTMENT_IDS = {10, 11, 12, 13, 14}
# 10 = Health & Body, 11 = Household, 12 = Baby & Child,
# 13 = Pet, 14 = Back to School


def is_food_department(product):
    """Check if a product belongs to a food department.

    Args:
        product: raw product dict from the API (must contain 'departments' key)

    Returns:
        True if the product is in a food department, False otherwise.
        Products with no department info are included (assumed food).
    """
    depts = product.get("departments", [])
    if not depts:
        return True
    dept_ids = {d.get("id") for d in depts if "id" in d}
    return not dept_ids.intersection(NON_FOOD_DEPARTMENT_IDS)


def create_session():
    """Create a requests.Session with Woolworths headers and seed cookies.

    Seeds the session with a GET / to establish baseline cookies and headers
    required for API calls. Each session should be used per-store to avoid
    cookie overwrites (see set_store_context).
    """
    session = requests.Session()
    session.headers.update(HEADERS)
    session.get(SITE_URL, timeout=15)
    return session


def set_store_context(session, fulfilment_store_id):
    """Set per-store pricing by injecting the cw-lrkswrdjp cookie.

    The cookie encodes `dm-Pickup,f-{fulfilmentStoreId},s-38`. The caller
    supplies the canonical store_id (= extra1 / fulfilmentStoreId) directly
    from data/woolworths_stores.csv — no lookup is needed.

    After injection, GETs /api/v1/shell to verify the store context took effect.
    A fresh session is required per store (the shell overwrites injected
    cookies on reused sessions).

    Args:
        session: a requests.Session (created by create_session())
        fulfilment_store_id: store's extra1 (fulfilmentStoreId) as str or int

    Returns:
        dict with keys: fulfilmentStoreId (int), method (str),
                        areaId (str|None), zone (str|None), distance (float|None)

    Raises:
        RuntimeError: if the shell still shows the default store (9171),
                     indicating the cookie was not accepted.
    """
    fsid = str(fulfilment_store_id)
    cookie_val = f"dm-Pickup,f-{fsid},s-38"
    session.cookies.set("cw-lrkswrdjp", cookie_val, domain="www.woolworths.co.nz", path="/")

    # Validate via shell
    resp = session.get(f"{BASE_URL}/shell", timeout=15)
    shell = resp.json()
    fulf = shell.get("context", {}).get("fulfilment", {})
    actual_fsid = fulf.get("fulfilmentStoreId")

    if actual_fsid == 9171 and fsid != "9171":
        raise RuntimeError(
            f"Cookie not accepted for store {fsid} — shell still shows default store (9171). "
            "Use a fresh session per store."
        )

    result = {
        "fulfilmentStoreId": actual_fsid,
        "method": fulf.get("method"),
        "areaId": fulf.get("areaId"),
        "zone": fulf.get("zone"),
        "distance": fulf.get("distance"),
    }
    return result


def create_session_and_set_store(fulfilment_store_id):
    """Convenience: create a fresh session and inject per-store cookie.

    Returns (session, store_context_dict).
    """
    session = create_session()
    context = set_store_context(session, fulfilment_store_id)
    return session, context


def search_products(session, query, size=20, food_only=True):
    """Search for products with the current store context.

    Args:
        session: a requests.Session with store context set via set_store_context()
        query: search term
        size: max results to return (default 20)
        food_only: if True, exclude non-food departments
                   (Health & Body, Household, Baby & Child, Pet, Back to School)

    Returns list of product dicts with keys: sku, name, brand, salePrice,
    originalPrice, isSpecial, unitPrice, volumeSize, cupMeasure, cupListPrice,
    url, imageUrl, department.
    """
    resp = session.get(
        f"{BASE_URL}/products",
        params={"target": "search", "search": query, "size": size},
        timeout=15,
    )
    data = resp.json()
    items = data.get("products", {}).get("items", [])
    results = []
    for item in items:
        if food_only and not is_food_department(item):
            continue
        price_info = item.get("price", {})
        size_info = item.get("size", {})
        departments = item.get("departments", [])
        dept_name = departments[0].get("name", "") if departments else ""
        results.append({
            "sku": item.get("sku"),
            "name": item.get("name", ""),
            "brand": item.get("brand", ""),
            "salePrice": price_info.get("salePrice"),
            "originalPrice": price_info.get("originalPrice"),
            "isSpecial": price_info.get("isSpecial", False),
            "unitPrice": size_info.get("cupPrice", ""),
            "volumeSize": size_info.get("volumeSize", ""),
            "cupMeasure": size_info.get("cupMeasure", ""),
            "cupListPrice": size_info.get("cupListPrice", ""),
            "url": item.get("url", ""),
            "imageUrl": item.get("imageUrl", ""),
            "department": dept_name,
        })
    return results


def find_cheapest(session, query, food_only=True, size=20):
    """Search for products and return the cheapest valid result.

    Args:
        session: a requests.Session with store context set
        query: search term
        food_only: if True, exclude non-food departments
        size: number of products to fetch before picking cheapest

    Returns:
        The cheapest product dict, or None if no priced products found.
    """
    products = search_products(session, query, size=size, food_only=food_only)
    priced = [p for p in products if p["salePrice"] is not None]
    if not priced:
        return None
    return min(priced, key=lambda p: p["salePrice"])


def get_nearby_stores(user_lat, user_lon, max_dist_km=5):
    """Return stores within max_dist_km, sorted by distance (closest first).

    Sources coordinates + canonical store_id (extra1 / fulfilmentStoreId)
    directly from data/woolworths_stores.csv (generated by
    woolworths_setup.fetch_store_data()).

    Returns list of dicts: {store_id (extra1), name, fulfilmentStoreId,
    lat, lon, distance_km}
    """
    if not STORE_CSV.exists():
        raise FileNotFoundError(f"Store CSV not found: {STORE_CSV}")

    nearby = []
    with open(STORE_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                lat = float(row["latitude"])
                lon = float(row["longitude"])
            except (ValueError, TypeError):
                continue
            store_id = row["id"]
            dist = haversine(user_lat, user_lon, lat, lon)
            if dist <= max_dist_km:
                nearby.append({
                    "store_id": store_id,
                    "name": row.get("name", ""),
                    "fulfilmentStoreId": store_id,
                    "lat": lat,
                    "lon": lon,
                    "distance_km": dist,
                })

    nearby.sort(key=lambda s: s["distance_km"])
    return nearby
