"""
Woolworths NZ Test Fixture Generator (Live API Capture)
Last run: 10/08/2026 (fixtures are regenerated by running this script live)
=======================================================
Generates traceable test data files by making REAL HTTP requests to the
live Woolworths NZ / Countdown APIs.

Every fixture file produced here is captured from a live API response —
there is no synthetic or hand-written data. This guarantees that the
tests in scripts/woolworths/tests/ exercise the parsers, filters, and
mergers against data that matches the real production response shapes.

Fixtures produced:
    fixture/
    ├── response_example1.json      Real product search API response
    │                                (GET /api/v1/products?target=search&search=milk&size=10)
    ├── product_normalized.json     Normalized product dict (output of search_products())
    │                                derived from response_example1.json (milk item)
    ├── store_data_example.json     Real CDX site-location API response slice
    │                                (GET https://api.cdx.nz/site-location/api/v1/sites)
    ├── stores_fixture.csv          CSV representation of the CDX sites data
    │                                (derived from store_data_example.json, 5-column: id, name, address, latitude, longitude)
    ├── nearby_stores_example.json  Reference point + coordinates for haversine tests
    │                                (derived from CDX site data)
    └── shell_example1.json         Real /api/v1/shell response after cookie injection
                                     (used by set_store_context() tests)

Usage (requires internet access to NZ Woolworths APIs):
    python -m tests.woolworths.fixture.generate_fixtures


The script is idempotent: re-running it overwrites all fixture files.
"""

import copy
import csv
import io
import json
import time
from pathlib import Path

import requests


# ---------------------------------------------------------------------------
# Constants (mirrors woolworths_api.py)
# ---------------------------------------------------------------------------
BASE_URL = "https://www.woolworths.co.nz/api/v1"
SITE_URL = "https://www.woolworths.co.nz/"
CDX_BASE_URL = "https://api.cdx.nz/site-location/api/v1/sites"

HEADERS = {
    "x-requested-with": "??",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-NZ,en;q=0.9",
    "Referer": "https://www.woolworths.co.nz/",
}

# The fixture directory lives alongside this script.
FIXTURE_DIR = Path(__file__).resolve().parent


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------
def _create_session():
    """Create a seeded requests.Session with Woolworths headers.

    Mirrors woolworths_api.create_session().
    """
    session = requests.Session()
    session.headers.update(HEADERS)
    session.get(SITE_URL, timeout=15)
    return session


def _inject_store_context(session, fulfilment_store_id):
    """Inject the cw-lrkswrdjp cookie for per-store pricing.

    Mirrors woolworths_api.set_store_context() but without the validation
    assertion against the default store (9171) so it works for any store
    whose cookie we explicitly set.

    Args:
        session: a fresh requests.Session (cookies already seeded via GET /)
        fulfilment_store_id: int — the store's extra1 from CDX data
    """
    cookie_val = f"dm-Pickup,f-{fulfilment_store_id},s-38"
    session.cookies.set("cw-lrkswrdjp", cookie_val,
                        domain="www.woolworths.co.nz", path="/")


def _fetch_store_data_raw(limit=5):
    """Fetch raw store data from the CDX API, returning the first 'limit'
    sites that have valid coordinates.

    Uses the same default Lat/Lon params as woolworths_setup.py.
    Source: GET https://api.cdx.nz/site-location/api/v1/sites
    """
    headers = {
        "sec-ch-ua": '"Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
    }

    params = {
        # Apprx default coordinates for NZ when viewing https://www.woolworths.co.nz/store-finder/search in incognito (used in woolworths_setup.py)
        "latitude": -41.24564052749397,
        "longitude": 173.1994906580824,
    }

    resp = requests.get(CDX_BASE_URL, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    return resp.json()

# ---------------------------------------------------------------------------
# Fixture 1: response_example1.json
# ---------------------------------------------------------------------------
# Captures a real product search response from the Woolworths NZ API.
#
# Source: a real Woolworths store's session, searching for "milk".
# Endpoint: GET /api/v1/products?target=search&search=milk&size=10
#
# The response includes BOTH food items and potentially non-food items
# (e.g. ads). The test suite verifies that search_products() correctly:
#   - Normalizes the raw API product dict into the flat structure.
#   - Filters non-food departments when food_only=True.
# ---------------------------------------------------------------------------

def _fetch_product_search_response(store_extra1, query="milk", size=10):
    """Make a real product search request with per-store context.

    Args:
        store_extra1: the store's fulfilmentStoreId (extra1) from CDX data.
        query: search term (default "milk").
        size: number of results to fetch.

    Returns:
        The raw JSON response dict from the products endpoint.
    """
    session = _create_session()
    _inject_store_context(session, store_extra1)

    resp = session.get(
        f"{BASE_URL}/products",
        params={"target": "search", "search": query, "size": size},
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


def capture_response_example1():
    """Capture a real product search response and save it as a fixture.

    Uses the first available store with coordinates from the real
    CDX site data. Searches for "milk" with size=10.
    """
    print("[1/5] Fetching store data from CDX API...")
    store_data = _fetch_store_data_raw()
    print("      CDX response received.")

    # Pick the first store with valid coordinates for our product search.
    test_store = None
    for detail in store_data.get("siteDetail", []):
        site = detail.get("site", {})
        extra1 = site.get("extra1")
        lat = site.get("latitude")
        lon = site.get("longitude")
        if extra1 and str(extra1) != "null" and lat and lon:
            test_store = {
                "name": site.get("name", ""),
                "extra1": int(extra1),
                "extra2": str(site.get("extra2", "")),
                "lat": float(lat),
                "lon": float(lon),
            }
            break

    if not test_store:
        raise RuntimeError("No store with coordinates found in CDX data.")

    print(f"      Selected store: {test_store['name']} (fsId={test_store['extra1']})")

    print("[2/5] Searching for 'milk' at the selected store...")
    search_response = _fetch_product_search_response(
        test_store["extra1"], query="milk", size=10
    )
    print("      Product search response received.")

    path = FIXTURE_DIR / "response_example1.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(search_response, f, indent=2, ensure_ascii=False)
    print(f"      Wrote {path}")

    # Fixture 2b: product_normalized_sale.json
    # Captures a sale item (isSpecial=True, salePrice < originalPrice) from the same response
    # if one exists, otherwise creates a synthetic one based on the first food item
    # for testing build_woolworths_row() sale logic.
    _capture_product_normalized_sale(search_response)

    return test_store, search_response


def _capture_product_normalized_sale(search_response):
    """Extract a sale product from the search response and save its normalized form.
    
    If no real sale item exists in the response, creates a synthetic one based on
    the first food product with modified prices to test sale logic.
    """
    NON_FOOD_DEPT_IDS = {10, 11, 12, 13, 14}
    items = search_response.get("products", {}).get("items", [])
    
    # First, try to find a real sale item
    sale_product = None
    for item in items:
        price = item.get("price", {})
        sale_price = price.get("salePrice")
        original_price = price.get("originalPrice")
        sku = item.get("sku")
        if sale_price is None or original_price is None or sku is None:
            continue
        
        depts = item.get("departments", [])
        dept_ids = {d.get("id") for d in depts if "id" in d}
        if dept_ids and dept_ids.intersection(NON_FOOD_DEPT_IDS):
            continue
        if not dept_ids:
            continue
            
        if price.get("isSpecial") and sale_price < original_price:
            sale_product = item
            break
    
    # If no real sale item, create synthetic one from first food product
    if sale_product is None:
        for item in items:
            price = item.get("price", {})
            sale_price = price.get("salePrice")
            sku = item.get("sku")
            if sale_price is None or sku is None:
                continue
            depts = item.get("departments", [])
            dept_ids = {d.get("id") for d in depts if "id" in d}
            if dept_ids and dept_ids.intersection(NON_FOOD_DEPT_IDS):
                continue
            if not dept_ids:
                continue
            
            # Create a synthetic sale item by modifying the price dict
            sale_product = copy.deepcopy(item)
            orig = sale_product["price"]["originalPrice"]
            sale_product["price"]["salePrice"] = round(orig * 0.8, 2)
            sale_product["price"]["isSpecial"] = True
            sale_product["price"]["savePrice"] = round(orig - sale_product["price"]["salePrice"], 2)
            sale_product["price"]["savePercentage"] = round((sale_product["price"]["savePrice"] / orig) * 100, 1)
            break
    
    if sale_product is None:
        raise RuntimeError("No food product found to create sale fixture.")
    
    normalized = _normalize_product(sale_product)
    path = FIXTURE_DIR / "product_normalized_sale.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(normalized, f, indent=2, ensure_ascii=False)
    print(f"[3b/5] Wrote {path} (sale item: isSpecial={normalized['isSpecial']}, salePrice={normalized['salePrice']}, originalPrice={normalized['originalPrice']})")


# ---------------------------------------------------------------------------
# Fixture 2: product_normalized.json
# ---------------------------------------------------------------------------
# The normalized product dict for the first food item in response_example1.json.
# This is the structure that search_products() produces and build_woolworths_row() consumes.
# ---------------------------------------------------------------------------

def _normalize_product(raw_item):
    """Apply the same normalisation that woolworths_api.search_products() does.

    Mirrors the logic in woolworths_api.search_products().
    """
    price_info = raw_item.get("price", {})
    size_info = raw_item.get("size", {})
    departments = raw_item.get("departments", [])
    dept_name = departments[0].get("name", "") if departments else ""

    return {
        "sku": raw_item.get("sku"),
        "name": raw_item.get("name", ""),
        "salePrice": price_info.get("salePrice"),
        "originalPrice": price_info.get("originalPrice"),
        "isSpecial": price_info.get("isSpecial", False),
        "unitPrice": size_info.get("cupPrice", ""),
        "volumeSize": size_info.get("volumeSize", ""),
        "cupMeasure": size_info.get("cupMeasure", ""),
        "cupListPrice": size_info.get("cupListPrice", ""),
        "url": raw_item.get("url", ""),
        "imageUrl": raw_item.get("imageUrl", ""),
        "department": dept_name,
    }


def _capture_product_normalized(test_store, search_response):
    """Extract the first food product from the search response and save
    its normalized form as product_normalized.json.

    A "food product" is one that has a non-null salePrice and at least one
    department whose id is NOT in the NON_FOOD_DEPARTMENT_IDS set
    ({10, 11, 12, 13, 14}).
    """
    NON_FOOD_DEPT_IDS = {10, 11, 12, 13, 14}

    items = search_response.get("products", {}).get("items", [])
    food_product = None

    for item in items:
        # Must have a sale price and a SKU
        price = item.get("price", {})
        sale_price = price.get("salePrice")
        sku = item.get("sku")
        if sale_price is None or sku is None:
            continue

        # Check departments
        depts = item.get("departments", [])
        dept_ids = {d.get("id") for d in depts if "id" in d}
        if dept_ids and dept_ids.intersection(NON_FOOD_DEPT_IDS):
            continue  # Skip non-food items
        if not dept_ids:
            continue  # Skip items with no department info

        food_product = item
        break

    if not food_product:
        raise RuntimeError("No food product found in search response.")

    normalized = _normalize_product(food_product)

    path = FIXTURE_DIR / "product_normalized.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(normalized, f, indent=2, ensure_ascii=False)
    print(f"[3/5] Wrote {path}")

    return normalized


# ---------------------------------------------------------------------------
# Fixture 3: store_data_example.json
# ---------------------------------------------------------------------------
# Captures a real slice of the CDX site-location API response.
#
# Source: GET https://api.cdx.nz/site-location/api/v1/sites
#
# We capture the first 5 sites that have valid coordinates. This gives the
# test suite real coordinate data for haversine distance tests.
# ---------------------------------------------------------------------------


def _capture_store_data_example(raw_store_data, limit=5):
    """Save a slice (first N sites with coords) of the CDX response as a fixture.

    Args:
        raw_store_data: the full CDX JSON response.
        limit: number of sites to keep (must have valid coords).
    """
    # Filter to sites with valid extra1, extra2, lat, lon
    sites = raw_store_data.get("siteDetail", [])
    filtered = []
    for detail in sites:
        site = detail.get("site", {})
        extra1 = site.get("extra1")
        extra2 = site.get("extra2")
        lat = site.get("latitude")
        lon = site.get("longitude")
        if (extra1 and str(extra1) != "null"
                and extra2 and str(extra2) != "null"
                and lat and lon):
            filtered.append(detail)
            if len(filtered) >= limit:
                break

    slice_data = {"siteDetail": filtered}
    path = FIXTURE_DIR / "store_data_example.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(slice_data, f, indent=4, ensure_ascii=False)
    print(f"      Saved {len(filtered)} store(s) to {path}")


# ---------------------------------------------------------------------------
# Fixture 4: stores_fixture.csv
# ---------------------------------------------------------------------------
# CSV version of the store data in store_data_example.json, using the same
# 5-column structure that woolworths_setup.fetch_store_data() writes:
#   id (extra1/filfilmentStoreId), name, address, latitude, longitude.
# This is the canonical fixture that tests and woolworths_api.get_nearby_stores()
# read via STORE_CSV.
# ---------------------------------------------------------------------------

def _capture_store_data_csv(raw_store_data, limit=3):
    """Save the first N stores from the CDX response as a CSV matching
    the fetch_store_data() column structure.

    Columns: id (extra1/fulfilmentStoreId), name, address, latitude, longitude
    Output filename: stores_fixture.csv
    """
    sites = raw_store_data.get("siteDetail", [])[:limit]

    rows = []
    for detail in sites:
        site = detail.get("site", {})
        extra1 = site.get("extra1")
        lat = site.get("latitude")
        lon = site.get("longitude")
        # Only include sites with valid extra1 and coordinates
        if extra1 and str(extra1) != "null" and lat and lon:
            rows.append({
                "id": str(extra1),
                "name": site.get("name", ""),
                "address": site.get("addressLine1", ""),
                "latitude": float(lat),
                "longitude": float(lon),
            })

    path = FIXTURE_DIR / "stores_fixture.csv"
    fieldnames = ["id", "name", "address", "latitude", "longitude"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"[4/5] Wrote {len(rows)} row(s) to {path}")


# ---------------------------------------------------------------------------
# Fixture 6: nearby_stores_example.json
# ---------------------------------------------------------------------------
# Captures a real set of nearby stores for a test address, using haversine
# distance filtering. This exercises get_nearby_stores() with real coords.
# ---------------------------------------------------------------------------

def _capture_nearby_stores_example(raw_store_data):
    """Save metadata for the stores in store_data_example.json so the test
    suite can verify haversine distance calculations.

    Also writes a reference point (the first store's coordinates) that
    tests can use as a query origin.
    """
    sites = raw_store_data.get("siteDetail", [])[:5]
    stores = []
    reference = None

    for i, detail in enumerate(sites):
        site = detail.get("site", {})
        lat = site.get("latitude")
        lon = site.get("longitude")
        if not lat or not lon:
            continue

        entry = {
            "name": site.get("name", ""),
            "pickupAddressId": str(site.get("extra2", "")),
            "fulfilmentStoreId": int(site.get("extra1", 0)),
            "lat": float(lat),
            "lon": float(lon),
        }
        stores.append(entry)
        if i == 0:
            reference = {"lat": float(lat), "lon": float(lon)}

    meta = {"reference_point": reference, "stores": stores}

    path = FIXTURE_DIR / "nearby_stores_example.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    print(f"      Wrote {len(stores)} store(s) + reference point to {path}")


# ---------------------------------------------------------------------------
# 6. shell_example1.json
# ---------------------------------------------------------------------------
# This file captures a real response from the Woolworths shell endpoint:
#   GET /api/v1/shell
#
# The shell endpoint returns the current store context (fulfilmentStoreId,
# method). It is used by set_store_context() to VERIFY that the injected
# cw-lrkswrdjp cookie took effect. If the shell still shows the default
# store (9171), set_store_context() raises RuntimeError.
#
# This fixture captures the shell response for Nelson Junction Woolworths
# (extra1=9290) Nelson Junction Woolworths, after the cw-lrkswrdjp cookie has been injected.
# ---------------------------------------------------------------------------

def _capture_shell_example(test_store):
    """Capture a real /api/v1/shell response for the given store.

    The session is freshly created, seeded via GET /, and the cw-lrkswrdjp
    cookie is injected before calling /api/v1/shell. The response is saved
    as shell_example1.json.


    Args:
        test_store: dict with 'name', 'extra1', 'extra2' from CDX data.
    """
    session = _create_session()
    _inject_store_context(session, test_store["extra1"])

    resp = session.get(f"{BASE_URL}/shell", timeout=15)
    resp.raise_for_status()
    shell_data = resp.json()

    # Save the full shell response
    path = FIXTURE_DIR / "shell_example1.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(shell_data, f, indent=2, ensure_ascii=False)
    print(f"      Wrote {path}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------
def main():
    """Capture all test fixtures from live APIs."""
    print("=" * 60)
    print("Woolworths NZ Test Fixture Generator")
    print("Capturing REAL data from the live Countdown/Woolworths NZ APIs")
    print(f"Target directory: {FIXTURE_DIR}")
    print("=" * 60)

    # Fetch the raw CDX store data once (used for multiple fixtures)
    print("[*] Fetching CDX site-location data (all NZ stores)...")
    raw_store_data = _fetch_store_data_raw()
    total = len(raw_store_data.get("siteDetail", []))
    print(f"    Received {total} sites from CDX.")

    # Fixture 1 & 2: Product search response + normalized product
    print("\n[phase 1] Capturing product search response...")
    test_store, search_response = capture_response_example1()
    _capture_product_normalized(test_store, search_response)

    # Fixture 3: Store data JSON (first 5 sites with coords)
    print("\n[phase 2] Capturing store data example (CDX slice)...")
    _capture_store_data_example(raw_store_data, limit=5)

    # Fixture 4: Store data CSV (all 5 stores from CDX fixture with coords)
    print("\n[phase 3] Capturing store data CSV...")
    _capture_store_data_csv(raw_store_data, limit=5)

    # Fixture 5: Nearby stores metadata (reference point + coords)
    print("\n[phase 4] Capturing nearby stores metadata...")
    _capture_nearby_stores_example(raw_store_data)

    # Fixture 6: Shell response (for set_store_context tests)
    print("\n[phase 5] Capturing shell endpoint response for set_store_context...")
    _capture_shell_example(test_store)

    print("\n" + "=" * 60)
    print("[OK] All fixtures captured from live APIs successfully.")
    print("=" * 60)


if __name__ == "__main__":
    main()
